### **SUPERSTORE DATA ANALYTICS PROJECT: FROM RAW DATA TO INTERACTIVE DASHBOARD**


### **Objectives:**

* Analyze a real-world retail dataset to understand sales, profitability, product, customer, and regional performance.
* Clean, transform, and prepare the data using Python and pandas for reliable analysis.
* Perform exploratory data analysis (EDA) to uncover trends, patterns, relationships, and potential data-quality issues.
* Develop visualizations to communicate key findings and business insights.
* Build an interactive sales and profitability dashboard using Python and Dash.
* Translate analytical findings into actionable insights that support data-driven business decisions.

### **Step 1: Dataset Selection**

This project uses the **Superstore retail dataset**, a transactional dataset designed to provide insight into the performance of a large retail business operating across different regions, product categories, and customer segments.

The dataset captures information about customer orders, products, sales, discounts, shipping, and profitability. It includes **order and shipping dates, shipping modes, customer and geographic information, product categories and sub-categories, quantities purchased, sales, discounts, and profit or loss**. These variables provide a foundation for examining how different products, regions, customer segments, and business activities contribute to overall performance.

**1.1. Dataset Highlights:**
- **Data Source:** Kaggle
- **Dataset:** Superstore Dataset
- **Published by:** Vivek Chowdhury
- **Data Structure:** 9994 Rows and 21 columns

- **URL:** https://www.kaggle.com/datasets/vivek468/superstore-dataset-final?resource=download

**1.2. Metadata**
- **Row ID** => Unique ID for each row.
- **Order ID** => Unique Order ID for each Customer.
- **Order Date** => Order Date of the product.
- **Ship Date** => Shipping Date of the Product.
- **Ship Mode**=> Shipping Mode specified by the Customer.
- **Customer ID** => Unique ID to identify each Customer.
- **Customer Name** => Name of the Customer.
- **Segment** => The segment where the Customer belongs.
- **Country** => Country of residence of the Customer.
- **City** => City of residence of of the Customer.
- **State** => State of residence of the Customer.
- **Postal Code** => Postal Code of every Customer.
- **Region** => Region where the Customer belong.
- **Product ID** => Unique ID of the Product.
- **Category** => Category of the product ordered.
- **Sub-Category** => Sub-Category of the product ordered.
- **Product Name** => Name of the Product
- **Sales** => Sales of the Product.
- **Quantity** => Quantity of the Product.
- **Discount** => Discount provided.
- **Profit** => Profit/Loss incurred.

## **Step 2. Data Wrangling: Load your dataset using Python (Pandas) and clean it.**

**2.1. Import required libraries**

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

**2.2. Load superstore data to pandas dataframe**

In [17]:
encodings = ["utf-8", "utf-8-sig", "iso-8859-1", "latin1", "cp1252", "mixed","windows-1252" ]
file_path = r"C:\Users\emman\OneDrive\Desktop\hero\project\1.Completed\Superstore_Data_Analytics_Project\1.Superstore_Dataset.csv"

for encoding in encodings:
  try:
    df = pd.read_csv(file_path, encoding=encoding)
    break
  except Exception:
    pass

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

**2.3. Basic insight from Superstore Dataset**

In [18]:
# Check the Data structure - summary of the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

**2.4. Handle missing values in the dataset**

In [19]:
# Checking for missing values
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

**2.5. Fix Data Types**

In [20]:
# Convert the date columns to pandas datatime datatype
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Check the datatype of the columns
df[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [21]:
# Converting text columns to string data type and remove whitespaces
text_columns = ['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State','Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name']

for column in text_columns:
  df[column] = df[column].astype('string').str.strip()

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   string
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   string
 5   Customer ID    9994 non-null   string
 6   Customer Name  9994 non-null   string
 7   Segment        9994 non-null   string
 8   Country        9994 non-null   string
 9   City           9994 non-null   string
 10  State          9994 non-null   string
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   string
 13  Product ID     9994 non-null   string
 14  Category       9994 non-null   string
 15  Sub-Category   9994 non-null   string
 16  Product Name   9994 non-null   string
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), string(13)
memory usage: 1.6 MB

**2.5. Handle duplicates in the dataset**

In [23]:
# 1. Remove Duplicates
df = df.drop_duplicates()

2.5.1 Check and fix duplicated Order ID and Product ID pair

In [24]:
# Number of duplicate orders
Duplicate_Order = df['Order ID'].duplicated().sum()
print(Duplicate_Order)

# Number of Unique Product ID for each Order ID
Test1=df.groupby('Order ID')['Product ID'].nunique().sort_values(ascending=False)
print(Test1.max())

4985
14

In [25]:
# Investigate duplicates orders
j=0
for i in range(0, Test1.max() + 1):
  print(f'The number of order id that has  {i} Product ID ',len(Test1[Test1==i]))
  j += i * len(Test1[Test1 == i])
print('Numbre of order id including duplicate with different product Id is ',j)

The number of order id that has  0 Product ID  0
The number of order id that has  1 Product ID  2540
The number of order id that has  2 Product ID  1218
The number of order id that has  3 Product ID  607
The number of order id that has  4 Product ID  333
The number of order id that has  5 Product ID  157
The number of order id that has  6 Product ID  70
The number of order id that has  7 Product ID  52
The number of order id that has  8 Product ID  15
The number of order id that has  9 Product ID  10
The number of order id that has  10 Product ID  3
The number of order id that has  11 Product ID  2
The number of order id that has  12 Product ID  1
The number of order id that has  13 Product ID  0
The number of order id that has  14 Product ID  1
Numbre of order id including duplicate with different product Id is  9986

In [26]:
# Filter and display all duplicate entries based on Order ID and Product ID
duplicates = df[df.duplicated(subset=['Order ID', 'Product ID'], keep=False)]

# Sort them so matching duplicates are right next to each other
duplicates_sorted = duplicates.sort_values(by=['Order ID', 'Product ID'])

# View key columns of the duplicate rows
duplicates_sorted[['Order ID', 'Order Date', 'Ship Date','Ship Mode','Product ID', 'Product Name', 'Segment', 'City','State', 'Postal Code','Region','Category','Sub-Category']]

,Order ID,Order Date,Ship Date,Ship Mode,Product ID,Product Name,Segment,City,State,Postal Code,Region,Category,Sub-Category
6498,CA-2015-103135,2015-07-24,2015-07-28,Standard Class,OFF-BI-10000069,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",Home Office,Louisville,Kentucky,40214,South,Office Supplies,Binders
6500,CA-2015-103135,2015-07-24,2015-07-28,Standard Class,OFF-BI-10000069,"GBC Prepunched Paper, 19-Hole, for Binding Sys...",Home Office,Louisville,Kentucky,40214,South,Office Supplies,Binders
350,CA-2016-129714,2016-09-01,2016-09-03,First Class,OFF-PA-10001970,Xerox 1881,Home Office,New York City,New York,10009,East,Office Supplies,Paper
352,CA-2016-129714,2016-09-01,2016-09-03,First Class,OFF-PA-10001970,Xerox 1881,Home Office,New York City,New York,10009,East,Office Supplies,Paper
1300,CA-2016-137043,2016-12-23,2016-12-25,Second Class,FUR-FU-10003664,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",Consumer,Springfield,Virginia,22153,South,Furniture,Furnishings
1301,CA-2016-137043,2016-12-23,2016-12-25,Second Class,FUR-FU-10003664,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",Consumer,Springfield,Virginia,22153,South,Furniture,Furnishings
9168,CA-2016-140571,2016-03-15,2016-03-19,Standard Class,OFF-PA-10001954,Xerox 1964,Home Office,Jackson,Mississippi,39212,South,Office Supplies,Paper
9169,CA-2016-140571,2016-03-15,2016-03-19,Standard Class,OFF-PA-10001954,Xerox 1964,Home Office,Jackson,Mississippi,39212,South,Office Supplies,Paper
7881,CA-2017-118017,2017-12-03,2017-12-06,Second Class,TEC-AC-10002006,Memorex Micro Travel Drive 16 GB,Consumer,Thornton,Colorado,80229,West,Technology,Accessories
7882,CA-2017-118017,2017-12-03,2017-12-06,Second Class,TEC-AC-10002006,Memorex Micro Travel Drive 16 GB,Consumer,Thornton,Colorado,80229,West,Technology,Accessories
3183,CA-2017-152912,2017-11-09,2017-11-12,Second Class,OFF-ST-10003208,Adjustable Depth Letter/Legal Cart,Corporate,Columbia,Maryland,21044,East,Office Supplies,Storage
3184,CA-2017-152912,2017-11-09,2017-11-12,Second Class,OFF-ST-10003208,Adjustable Depth Letter/Legal Cart,Corporate,Columbia,Maryland,21044,East,Office Supplies,Storage
3405,US-2014-150119,2014-04-23,2014-04-27,Standard Class,FUR-CH-10002965,Global Leather Highback Executive Chair with P...,Home Office,Columbus,Ohio,43229,East,Furniture,Chairs
3406,US-2014-150119,2014-04-23,2014-04-27,Standard Class,FUR-CH-10002965,Global Leather Highback Executive Chair with P...,Home Office,Columbus,Ohio,43229,East,Furniture,Chairs
430,US-2016-123750,2016-04-15,2016-04-21,Standard Class,TEC-AC-10004659,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,Home Office,Gastonia,North Carolina,28052,South,Technology,Accessories
431,US-2016-123750,2016-04-15,2016-04-21,Standard Class,TEC-AC-10004659,Imation Secure+ Hardware Encrypted USB 2.0 Fla...,Home Office,Gastonia,North Carolina,28052,South,Technology,Accessories

In [27]:
len(duplicates_sorted)

16

In [28]:
# 1. Identify columns to update
target_cols = ['Sales', 'Quantity', 'Profit']
df['Quantity'] = df['Quantity'].astype(float)

# 2. Calculate group means for duplicate Order ID + Product ID pairs and assign directly
df.loc[duplicates_sorted.index, target_cols] = df.groupby(['Order ID', 'Product ID'])[target_cols].transform('mean')

# 3. Now drop the duplicate rows, keeping the first occurrence (which now holds the mean values)
df_cleaned = df.drop_duplicates(subset=['Order ID', 'Product ID','Product Name'], keep='first')

df = df_cleaned

df.shape

(9986, 21)

2.5.2 Check and fix duplicated Product ID and Product Name pair

In [29]:
# Investigate data for consistency between Product ID and Product Name
print('the number of product name', len(df['Product Name'].unique()))
print('the number of product ID',len(df['Product ID'].unique()))

the number of product name 1850
the number of product ID 1862

In [30]:
# Check product IDs with more than one product name
Test=df.groupby('Product ID')['Product Name'].nunique().sort_values(ascending=False)
print(len(Test[Test==2]))
print(len(Test[Test==1]))
print(len(Test[Test==0]))

32
1830
0

In [31]:
# Display all product ID that have 2 products name  along with product name
pro_ids=Test[Test==2].index
df[df['Product ID'].isin(pro_ids)][['Product ID', 'Product Name']].drop_duplicates().sort_values('Product ID')

           Product ID                                       Product Name
2471  FUR-BO-10002213   Sauder Forest Hills Library, Woodland Oak Finish
2115  FUR-BO-10002213              DMI Eclipse Executive Suite Bookcases
66    FUR-CH-10001146        Global Value Mid-Back Manager's Chair, Gray
128   FUR-CH-10001146                           Global Task Chair, Black
1459  FUR-FU-10001473                            DAX Wood Document Frame
...               ...                                                ...
1219  TEC-PH-10002200                              Samsung Galaxy Note 2
2596  TEC-PH-10002310  Plantronics Calisto P620-M USB Wireless Speake...
1378  TEC-PH-10002310                 Panasonic KX T7731-B Digital phone
922   TEC-PH-10004531      OtterBox Commuter Series Case - iPhone 5 & 5s
2713  TEC-PH-10004531                                        AT&T CL2909

[64 rows x 2 columns]

In [32]:
# Calculate the most frequent name ONLY for the 32 affected Product IDs
most_frequent_names = (df[df['Product ID'].isin(pro_ids)].groupby('Product ID')['Product Name'].agg(lambda x: x.mode()[0]).to_dict())

# Convert dictionary items to a clean 2-column DataFrame
d = pd.DataFrame(list(most_frequent_names.items()), columns=['Product ID', 'Product Name'])
d.duplicated().value_counts()

False    32
Name: count, dtype: int64

In [33]:
# Apply the mapping ONLY to the rows matching those 32 Product IDs
df.loc[df['Product ID'].isin(pro_ids), 'Product Name'] = (df['Product ID'].map(most_frequent_names))

In [34]:
# Confirm that one product ID is mapped to one product name
Test3=df.groupby('Product ID')['Product Name'].nunique().sort_values(ascending=False)
Test3.max()
# should be 1

np.int64(1)

**2.6. Feature Engineering - Create new columns**

In [35]:
# Add Year, Month and Day columns from Order Date
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day'] = df['Order Date'].dt.day

# Create Month_Year column
df['Month_Year'] = df['Order Date'].dt.to_period('M').astype(str)

In [36]:
# Add Profit Magin column that calculate Profit per Sales
df['Profit_Margin'] = np.where(df['Sales'] != 0, df['Profit'] / df['Sales'], 0)

In [37]:
# Add Shipping Days column that calucate the number of days between order & shippinG
df["Ship Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [38]:
# Confirm the added Columns
df[['Year', 'Month', 'Day', 'Month_Year', "Order Date", "Ship Date", "Ship Days", 'Profit_Margin', ]].head()

   Year  Month  Day Month_Year Order Date  Ship Date  Ship Days  Profit_Margin
0  2016     11    8    2016-11 2016-11-08 2016-11-11          3         0.1600
1  2016     11    8    2016-11 2016-11-08 2016-11-11          3         0.3000
2  2016      6   12    2016-06 2016-06-12 2016-06-16          4         0.4700
3  2015     10   11    2015-10 2015-10-11 2015-10-18          7        -0.4000
4  2015     10   11    2015-10 2015-10-11 2015-10-18          7         0.1125

In [39]:
df['Ship Days'].unique()

array([3, 4, 7, 5, 2, 6, 1, 0])

**2.7. Data Structure after cleaning and feature engineering**

In [40]:
# Data structure after Cleaning
print(df.shape)

(9986, 27)

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 9986 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9986 non-null   int64
 1   Order ID       9986 non-null   string
 2   Order Date     9986 non-null   datetime64[us]
 3   Ship Date      9986 non-null   datetime64[us]
 4   Ship Mode      9986 non-null   string
 5   Customer ID    9986 non-null   string
 6   Customer Name  9986 non-null   string
 7   Segment        9986 non-null   string
 8   Country        9986 non-null   string
 9   City           9986 non-null   string
 10  State          9986 non-null   string
 11  Postal Code    9986 non-null   int64
 12  Region         9986 non-null   string
 13  Product ID     9986 non-null   string
 14  Category       9986 non-null   string
 15  Sub-Category   9986 non-null   string
 16  Product Name   9986 non-null   string
 17  Sales          9986 non-null   float64
 18  Quantity       9986 non-null   float64
 19  Discount       9986 non-null   float64
 20  Profit         9986 non-null   float64
 21  Year           9986 non-null   int32
 22  Month          9986 non-null   int32
 23  Day            9986 non-null   int32
 24  Month_Year     9986 non-null   str
 25  Profit_Margin  9986 non-null   float64
 26  Ship Days      9986 non-null   int64
dtypes: datetime64[us](2), float64(5), int32(3), int64(3), str(1), string(13)
memory usage: 2.3 MB

**2.8 Export the Cleaned Superstore Dataset for Analysis**

In [42]:
# Export the clean dataset
file_path = r"C:\Users\emman\OneDrive\Desktop\hero\project\1.Completed\Superstore_Data_Analytics_Project\3.Cleaned_Superstore_Dataset.csv"

df.to_csv(file_path, encoding='utf-8', index=False)

In [43]:
# Verify the cleaned superstore dataset
file_path = r"C:\Users\emman\OneDrive\Desktop\hero\project\1.Completed\Superstore_Data_Analytics_Project\3.Cleaned_Superstore_Dataset.csv"
df = pd.read_csv(file_path)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Year,Month,Day,Month_Year,Profit_Margin,Ship Days
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2.0,0.00,41.9136,2016,11,8,2016-11,0.1600,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3.0,0.00,219.5820,2016,11,8,2016-11,0.3000,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2.0,0.00,6.8714,2016,6,12,2016-06,0.4700,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5.0,0.45,-383.0310,2015,10,11,2015-10,-0.4000,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2.0,0.20,2.5164,2015,10,11,2015-10,0.1125,7